"""
Convert the ESP files generated by Multiwfn into ply mesh format.

Running in Terminal with:
python 5.VerticesToPLYMesh_mp.py
"""

import multiprocessing
from DeepHostGuest.data_augmentation.from_vtx_to_mesh import *
import os
from tqdm import tqdm

# Base Calculation Directory for xTB
basedir = '/path/to/xtb_out'

names = os.listdir(basedir)
no_pdb = []

if __name__ == "__main__":

    def process_file(folder):
        os.chdir(os.path.join(basedir, folder))
        if "vtx.ply" in os.listdir(os.getcwd()):
            return
        elif "vtx.pdb" not in os.listdir(os.getcwd()):
            no_pdb.append(folder)
        else:
            pdb_file = 'vtx.pdb'
            ply_file = 'vtx.ply'
            surf = get_polydata_connectivity_remove(pdb_file)
            esp = surf_to_mesh(surf, ply_file)


    with multiprocessing.Pool(processes=32) as pool:
        pool.map(process_file, names)
